server:
  port: 15001
spring:
  application:
    name: zuul
  datasource:
    url: jdbc:mysql://localhost:3306/edge_computing_service?serverTimezone=UTC
    username: root
    password: a128263
eureka:
  instance:
    hostname: zuul
  client:
    service-url:
      defaultZone: http://localhost:15000/eureka/


zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    admin:
      path: /admin-service/**
      serviceId: admin-service
    device:
      path: /device-service/**
      serviceId: device-service
    convoy:
      path: /convoy-service/**
      serviceId: convoy-service
    prisoner:
      path: /prisoner-service/**
      serviceId: prisoner-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
ribbon:
  ConnectTimeout: 500000
  ReadTimeout: 500000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
