server:
  port: 15001
spring:
  application:
    name: zuul
  datasource:
    url: jdbc:mysql://localhost:3306/my?serverTimezone=UTC
    username: root
    password: a128263
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
eureka:
  instance:
    hostname: zuul
  client:
    service-url:
      defaultZone: http://localhost:15000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000
ribbon:
  ConnectTimeout: 500000 # 连接超时时间(ms)
  ReadTimeout: 500000 # 通信超时时间(ms)
  MaxAutoRetries: 0  #不重试
  MaxAutoRetriesNextServer: 0 #不尝试下一台机器
