spring:
  application:
    name: eureka
server:
  port: 15000
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:15000/eureka

