spring:
  application:
    name: convoy-service
  datasource:
    url: jdbc:mysql://localhost:3306/edge_computing_service_zunei?serverTimezone=UTC
    username: root
    password: a128263
server:
  port: 15003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:15000/eureka/
    healthcheck:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
