spring:
  application:
    name: convoy-service
  datasource:
#    url: jdbc:mysql://localhost:3306/edge_computing_service_zunei?serverTimezone=UTC
#    username: root
#    password: a128263
    url: jdbc:mysql://10.109.246.54:3306/dfl_edge_computing_service?serverTimezone=UTC
    username: root
    password: hadoop
    #driver-class-name: com.mysql.jdbc.Driver
server:
  port: 15003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:15000/eureka/
    healthcheck:
      enabled: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
