spring:
  application:
    name: prisoner-service
  datasource:
    url: jdbc:mysql://localhost:3306/my?serverTimezone=UTC
    username: root
    password: a128263
server:
  port: 15005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:15000/eureka/
    healthcheck:
      enabled: true


